# Generated by Django 5.2.3 on 2025-08-04 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('address', models.CharField(default='', max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('contact_information', models.TextField(blank=True, default='')),
                ('pocket_money', models.IntegerField(default=0)),
                ('meals_offered', models.CharField(blank=True, default='', max_length=100)),
                ('dayoffs', models.CharField(blank=True, default='', max_length=100)),
                ('allowance', models.CharField(blank=True, default='', max_length=100)),
                ('facilities', models.TextField(blank=True, default='')),
                ('other', models.TextField(blank=True, default='')),
                ('expected_duration', models.CharField(blank=True, default='', max_length=100)),
                ('expected_licenses', models.CharField(choices=[('None', 'None'), ('Driving', 'Driving License'), ('Motorcycle', 'Motorcycle License'), ('Both', 'Both Licenses')], default='None', max_length=20)),
                ('expected_age', models.CharField(blank=True, default='', max_length=50)),
                ('expected_gender', models.CharField(blank=True, default='', max_length=10)),
                ('expected_personality', models.TextField(blank=True, default='')),
                ('expected_other_requirements', models.TextField(blank=True, default='')),
                ('recruitment_slogan', models.TextField(blank=True, default='')),
                ('avg_rating', models.FloatField(blank=True, default=0.0)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
