# Generated by Django 5.2.3 on 2025-12-28 08:40

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(default="", max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=15)),
                ("contact_information", models.TextField(blank=True, default="")),
                ("description", models.TextField()),
                ("pocket_money", models.IntegerField(default=0)),
                (
                    "meals_offered",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("dayoffs", models.CharField(blank=True, default="", max_length=100)),
                ("facilities", models.TextField(blank=True, default="")),
                ("other", models.TextField(blank=True, default="")),
                (
                    "expected_duration",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "vehicle",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Driving", "Driving License"),
                            ("Motorcycle", "Motorcycle License"),
                            ("Both", "Both Licenses"),
                        ],
                        default="None",
                        max_length=20,
                    ),
                ),
                ("recruitment_slogan", models.TextField(blank=True, default="")),
                (
                    "host_image",
                    models.ImageField(blank=True, null=True, upload_to="host_images"),
                ),
                ("avg_rating", models.FloatField(blank=True, default=0.0)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_updated_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("work_time", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("expected_duration", models.CharField(max_length=100)),
                ("expected_age", models.CharField(max_length=100)),
                ("expected_gender", models.CharField(max_length=100)),
                ("expected_licenses", models.CharField(max_length=100)),
                ("expected_personality", models.TextField()),
                ("expected_other_requirements", models.TextField()),
                (
                    "other_questions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "vacancy_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="vacancy_images"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Recruiting", "Recruiting"),
                            ("Full", "Full"),
                            ("Unavailable", "Unavailable"),
                        ],
                        default="Recruiting",
                        max_length=20,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="host.host"
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_updated_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
