# Generated by Django 5.2.3 on 2026-03-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_vacancyavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='name',
            field=models.CharField(default='Unknown Host', max_length=100),
            preserve_default=False,
        ),
    ]
