# Generated by assistant
import json

from django.db import migrations, models


def _text_to_json_list(apps, schema_editor):
    Host = apps.get_model("host", "Host")
    for host in Host.objects.all().iterator():
        value = host.contact_information

        if value in (None, ""):
            host.contact_information = "[]"
        elif isinstance(value, str):
            raw = value.strip()
            if raw == "":
                host.contact_information = "[]"
            else:
                try:
                    parsed = json.loads(raw)
                    # Keep if already valid JSON; normalize shape to list
                    if isinstance(parsed, list):
                        host.contact_information = json.dumps(parsed, ensure_ascii=False)
                    elif isinstance(parsed, dict):
                        host.contact_information = json.dumps([parsed], ensure_ascii=False)
                    else:
                        host.contact_information = json.dumps([{"value": raw}], ensure_ascii=False)
                except Exception:
                    host.contact_information = json.dumps([{"value": raw}], ensure_ascii=False)
        else:
            host.contact_information = "[]"

        host.save(update_fields=["contact_information"])


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0006_alter_host_vehicle_default_empty"),
    ]

    operations = [
        migrations.RunPython(_text_to_json_list, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="host",
            name="contact_information",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
