
# Generated by assistant to add counters and parent support
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		("forum", "0002_add_forum_images"),
	]

	operations = [
		migrations.AddField(
			model_name="forumthread",
			name="like_count",
			field=models.IntegerField(default=0),
		),
		migrations.AddField(
			model_name="forumreply",
			name="parent",
			field=models.ForeignKey(
				to="forum.forumreply",
				on_delete=django.db.models.deletion.CASCADE,
				null=True,
				blank=True,
				related_name="child_replies",
			),
		),
		migrations.AddField(
			model_name="forumreply",
			name="like_count",
			field=models.IntegerField(default=0),
		),
	]
