# Generated by Django 5.2.3 on 2025-12-28 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
        ("helper", "0003_add_work_experience_to_helpermodel"),
        ("host", "0002_update_application_to_use_vacancy"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("helper", "vacancy")},
        ),
        migrations.AddField(
            model_name="application",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="vacancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="host.vacancy",
            ),
        ),
        migrations.RemoveField(
            model_name="application",
            name="cover_letter",
        ),
        migrations.RemoveField(
            model_name="application",
            name="host",
        ),
        migrations.RemoveField(
            model_name="application",
            name="responded_at",
        ),
    ]
