# Generated by Django 5.2.3 on 2025-09-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpermodel',
            old_name='hobbits',
            new_name='hobbies',
        ),
    ]
