# Generated by Django 5.2.3 on 2026-03-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_rename_hobbits_helpermodel_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=10),
        ),
    ]
