# Generated by Django 5.2.3 on 2025-12-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helper", "0002_rename_hobbits_helpermodel_hobbies"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpermodel",
            name="work_experience",
            field=models.TextField(blank=True, default=""),
        ),
    ]
