# Generated by Django 5.2.3 on 2026-04-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_alter_helpermodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpermodel',
            name='birthday',
            field=models.DateField(blank=True, help_text='Unset until the user completes their profile (e.g. social signup).', null=True),
        ),
    ]
