# Generated by Django
import django.contrib.postgres.fields
from django.db import migrations, models

def convert_experiences_to_array(apps, schema_editor):
    """Convert JSONB experiences to text array and save to the new temporary field."""
    HelperResume = apps.get_model('helper_resume', 'HelperResume')
    
    for resume in HelperResume.objects.all():
        old_data = resume.experiences
        new_data = []
        
        if old_data:
            if isinstance(old_data, list):
                for exp in old_data:
                    if isinstance(exp, dict):
                        new_data.append(exp.get('title', ''))
                    elif isinstance(exp, str):
                        new_data.append(exp)
            elif isinstance(old_data, str):
                import json
                try:
                    parsed = json.loads(old_data)
                    if isinstance(parsed, list):
                        for exp in parsed:
                            if isinstance(exp, dict):
                                new_data.append(exp.get('title', ''))
                            elif isinstance(exp, str):
                                new_data.append(exp)
                except (json.JSONDecodeError, TypeError):
                    pass
        
        # 使用 update 寫入暫存欄位，避免觸發 save() 造成不可預期的 side effect
        HelperResume.objects.filter(pk=resume.pk).update(experiences_new=new_data)


def reverse_convert(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('helper_resume', '0001_initial'), # 請確保這裡依賴你的上一個 migration
    ]

    operations = [
        # 1. 新增一個暫存的 ArrayField
        migrations.AddField(
            model_name='helperresume',
            name='experiences_new',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500), 
                blank=True, 
                default=list, 
                size=None
            ),
        ),
        
        # 2. 執行資料轉換，將舊的 JSONB 資料整理後寫入暫存欄位
        migrations.RunPython(convert_experiences_to_array, reverse_convert),
        
        # 3. 移除舊的 JSONB 欄位
        migrations.RemoveField(
            model_name='helperresume',
            name='experiences',
        ),
        
        # 4. 將暫存欄位改名為原本的欄位名稱
        migrations.RenameField(
            model_name='helperresume',
            old_name='experiences_new',
            new_name='experiences',
        ),
    ]