# Generated by Django 5.2.3 on 2025-08-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('helper', 'Helper'), ('host', 'Host'), ('both', 'Both Helper and Host')], default='helper', help_text='Type of user: helper, host, or both', max_length=10),
        ),
    ]
