# Generated by assistant
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                to="post.Comment",
                on_delete=django.db.models.deletion.CASCADE,
                null=True,
                blank=True,
                related_name="replies",
            ),
        ),
    ]
